config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#index'
  resources :users do
    resources :reviews, only: %i[index new create]
    member do
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  resources :posts_g do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_gs, only: %i[create destroy]
  end

  resources :posts_c do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_cs, only: %i[create destroy]
  end

  resources :groups, only: :index do
    resources :messages, only: %i[index create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

  resources :notifications, only: %i[index destroy]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'

  resources :relationships, only: %i[create destroy]

  get '/posts_g/:id/destroy', to: 'posts_g#destroy'
  get '/posts_c/:id/destroy', to: 'posts_c#destroy'

  get '/groups/:id/create', to: 'groups#create'
end

app/models/post_c.rb
class PostC < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  validates :title, presence: true
  validates :region, presence: true
  validates :datetime, presence: true
  validates :charge, presence: true
  validates :payment, presence: true
  validates :content, presence: true

  belongs_to :giver, class_name: 'User', foreign_key: 'giver_id'
  has_many :post_c_takers, dependent: :destroy
  has_many :takers, through: :post_c_takers, dependent: :destroy

  has_many :favorite_cs, dependent: :destroy
  has_many :notifications, dependent: :destroy

  acts_as_taggable

  mount_uploader :image, ImageUploader

  def self.search(search)
    if search != ""
      PostC.where('title LIKE(?)', "%#{search}%")
    else
      PostC.all
    end
  end

  def create_notification_apply_c!(current_user, user, post)
    notification = current_user.active_notifications.new(
      post_c_id: post.id,
      visited_id: user.id,
      action: 'apply_c'
    )
    notification.save if notification.valid?
  end

  def create_notification_cancel_c!(current_user, user, post)
    notification = current_user.active_notifications.new(
      post_c_id: post.id,
      visited_id: user.id,
      action: 'cancel_c'
    )
    notification.save if notification.valid?
  end

  def create_notification_favorite_c!(current_user, user, post)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_c_id = ? and action = ? ", current_user.id, user.id, post.id, 'favorite'])
    return unless temp.blank?

    notification = current_user.active_notifications.new(
      post_c_id: post.id,
      visited_id: user.id,
      action: 'favorite_c'
    )
    notification.save if notification.valid?
  end
end

app/controllers/posts_g_controller.rb
class PostsGController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, except: %i[index new create]
  layout 'no_wrapper', only: :index

  def index
    @posts = PostG.includes(:giver)
    @tags = PostG.all_tags.order("taggings_count DESC").pluck(:name)

    if params[:keyword]
      @posts = PostG.search(params[:keyword])
    elsif params[:tag_name]
      @posts = PostG.tagged_with(params[:tag_name].to_s)
    end
  end

  def show
    @user = @post.giver
    reviews = Review.where(reviewee_id: @user.id)
    @count = reviews.count

    if user_signed_in?
      group_ids = @user.groups.pluck(:id)
      group_users = GroupUser.where(group_id: group_ids)
      group_user = group_users.where(user_id: current_user.id)
      @group_id = group_user.pluck(:group_id).first

      @favorite = @post.favorite_gs.where(user_id: current_user.id)
    end

    @takers = @post.takers
  end

  def new
    @post = PostG.new
  end

  def create
    @post = PostG.create(post_params)
    if @post.save
      flash[:notice] = '投稿しました。'
      redirect_to posts_g_path(@post)
    else
      flash[:alert] = '入力に不備があります。'
      render "new"
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = '投稿を編集しました。'
      redirect_to posts_g_path(@post)
    else
      flash[:alert] = '入力に不備があります。'
      render "edit"
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = '投稿を削除しました。'
    redirect_to root_path
  end

  def take
    @post.create_notification_apply_g!(current_user, @post.giver, @post)
    PostGTaker.create(post_g_id: @post.id, taker_id: current_user.id)
    flash[:notice] = '申し込みが完了しました。'
    redirect_to action: "show"
  end

  def cancel
    @post.create_notification_cancel_g!(current_user, @post.giver, @post)
    post_taker = PostGTaker.find_by(post_g_id: @post.id, taker_id: current_user.id)
    post_taker.destroy
    flash[:notice] = 'キャンセルが完了しました。'
    redirect_to action: "show"
  end

  private

  def post_params
    params.require(:post_g).permit(:title, :tag_list, :image, :region, :datetime, :content, :charge, :payment).merge(giver_id: current_user.id)
  end

  def set_post
    @post = PostG.find(params[:id])
  end
end

app/views/posts_g/_favorite.html.haml
- if user_signed_in?
  - if user.id != current_user.id
    - if favorite.empty?
      = link_to posts_g_favorite_gs_path(post.id), method: :post, remote: true do
        = icon('far', 'bookmark', class: "Post_bookmark--Icon")
    - else
      = link_to posts_g_favorite_gs_path(post.id), method: :delete, remote: true do
        = icon('fas', 'bookmark', class: "Post_bookmark--Icon")
- else
  = link_to posts_g_favorite_gs_path(post.id), method: :post do
    = icon('far', 'bookmark', class: "Post_bookmark--Icon")

app/views/posts_g/_form.html.haml
= javascript_include_tag 'postImage'

.Post_form
  = form_with(model: @post, url: "/posts_g/#{@post.id}", local: true) do |f|
    .Post_form__Content.Text
      = f.label "タイトル"
      %span.Required 必須
      %br/
      = f.text_field :title, autofocus: true, class: "Post_form__Content__Field"
    .Post_form__Content.Text
      = f.label "タグ"
      %span.Required.Non-required 任意
      %span
        = "※スペースかカンマで区切ってください"
      %br/
      = f.text_field :tag_list, value: @post.tag_list.join(' '), class: "Post_form__Content__Field"
    .Post_form__Content.Text
      = f.label "画像"
      %span.Required.Non-required 任意
      %br/
      = f.file_field :image, id: "Post_image_input"
      #Post_image_prev
        - if @post.image?
          = image_tag @post.image.url
    .Post_form__Content.Text
      = f.label "旅行したい場所"
      %span.Required 必須
      %br/
      = f.text_field :region, class: "Post_form__Content__Field"
    .Post_form__Content.Text
      = f.label "希望日時"
      %span.Required 必須
      %br/
      = f.text_field :datetime, class: "Post_form__Content__Field"
    .Post_form__Content.Text
      = f.label "希望料金"
      %span.Required 必須
      %br/
      = f.text_field :charge, class: "Post_form__Content__Field"
    .Post_form__Content.Text
      = f.label "お支払い方法"
      %span.Required 必須
      %br/
      = f.select :payment, [["現地で手渡し"],["事前振り込み"],["事後振り込み"]], prompt: "選択してください"
    .Post_form__Content.Text
      = f.label "リクエスト内容"
      %span.Required 必須
      %br/
      = f.text_area :content, rows: "15", class: "Post_form__Content__Field--Large"
    = f.submit "投稿", class: "Post_form__Btn Btn Text"

app/views/posts_g/_post.html.haml
= link_to posts_g_path(post) do
  .Post_box_outer
    .Post_box
      .Post_box__Left
        .Post_box__Left__Image
          - if post.giver.profile_image?
            = image_tag post.giver.profile_image.url, class: "Post_box__Left__Image"
          - else
            = image_tag "no-image.jpg", class: "Post_box__Left__Image"
        .Post_box__Left__Other
          .Post_index_username
            = post.giver.name
          .Post_index_review
            .Star_rating
              = image_tag "stars.jpg", class: "Front", width: "#{post.giver.avg_score*20}%"
              = image_tag "stars_gray.jpg"
            .Review_info
              = post.giver.avg_score
          .Text
            = "(#{post.giver.reviews.count}件のレビュー)"
      .Post_box__Right
        .Post_box__Right__Title
          = post[:title]
        .Tag_list
          - post.tag_list.each do |tag|
            .tag.Text
              = tag
        .Post_box__Right__Text.Text
          .table
            .tr
              .th 場所
              .td
                = post.region
            .table_lower
              .tr
                .th 日時
                .td_date
                  = post.datetime
              .tr
                .th 料金
                .td_charge
                  = post.charge

app/views/posts_g/edit.html.haml
.Title.Form_title
  = link_to 'javascript:history.back()' do
    = icon('fas', 'chevron-left', class: "Back_btn")
  = "投稿を編集する"
= render partial: "form"

app/views/posts_g/index.html.haml
.Post_index_wrapper
  .Post_index_wrapper__Inner
    .Post_index_left
      .Title
        = link_to 'javascript:history.back()' do
          = icon('fas', 'chevron-left', class: "Back_btn")
        = "ツアーゲストを探す"
      .Search_title.Bold
        条件で絞り込む
      .Keyword
        = form_with(url: posts_g_index_path, local: true, method: :get, class: "Keyword__Form") do |f|
          .Keyword__Form__Input
            = f.text_field :keyword, placeholder: "キーワードを入力", class: "Keyword__Form__Input__Text"
            = button_tag type: 'submit', class: "Keyword__Form__Input__Btn" do
              = icon('fas', 'search')
      .Tag_list
        - @tags.each do |tag|
          = link_to posts_g_index_path(tag_name: tag) do
            .tag
              = tag
    .Post_index_right
      .Title ツアーゲストの投稿一覧
      .Post_index_title
        = icon('fas', 'list')
        = "投稿一覧"
      - if @posts.empty?
        = render "layouts/empty"
      - else
        .Post_index
          - @posts.each do |post|
            = render partial: "post", locals: { post: post }

app/views/posts_g/new.html.haml
.Title.Form_title
  = link_to 'javascript:history.back()' do
    = icon('fas', 'chevron-left', class: "Back_btn")
  = "ツアーゲストとして投稿する"
= render partial: "form"

app/views/posts_g/show.html.haml
= javascript_include_tag 'map'

.Post_show_wrapper

  -# 投稿者の情報
  .Post_user_info
    .Post_user_info__Person
      投稿者
    = link_to user_path(@user) do
      - if @user.profile_image?
        = image_tag @user.profile_image.url, class: "Post_user_info__Image"
      - else
        = image_tag "no-image.jpg", class: "Post_user_info__Image"
    .Post_user_info__Name.Bold
      = @user.name
    .Post_user_info__Review
      .Star_rating
        = image_tag "stars.jpg", class: "Front", width: "#{@user.avg_score*20}%"
        = image_tag "stars_gray.jpg"
      = @user.avg_score
    = link_to "(#{@count}件のレビュー)", "/users/#{@user.id}/reviews"
    .Post_user_info__Follow_counts
      .Follow_count.Left
        = link_to followings_user_path(@user.id) do
          %span
            = @user.followings.count
          = "フォロー"
      .Follow_count#Follower_count
        = render "relationships/follower_count"

    -# ボタン
    .Btns
      - if user_signed_in?
        - if @user.id == current_user.id
          = link_to edit_posts_g_path(@post.id), method: :get do
            .White_btn
              .White_btn__Content
                = icon('fas', 'edit')
                = '投稿を編集する'
          = link_to "/posts_g/#{@post.id}/destroy", data: { confirm: "削除しますか？" } do
            .White_btn
              .White_btn__Content
                = icon('fas', 'trash')
                = '投稿を削除する'
        - else
          .Follow
            = render "relationships/follow", user: @user
          - if @group_id.nil?
            = link_to "/groups/#{@user.id}/create" do
              .White_btn
                .White_btn__Content
                  = icon('fas', 'paper-plane')
                  = "メッセージを送る"
          - else
            = link_to group_messages_path(@group_id, user_id: @user.id) do
              .White_btn
                .White_btn__Content
                  = icon('fas', 'paper-plane')
                  = "メッセージを送る"
      - else
        .Follow
          = render "relationships/follow", user: @user
        = link_to "/groups/#{@user.id}/create" do
          .White_btn
            .White_btn__Content
              = icon('fas', 'paper-plane')
              = "メッセージを送る"

    -# 申込済みユーザー
    .Takers
      .Takers_title.Bold
        この投稿の
        %br
        申込済みユーザー
      - if @takers.empty?
        .Takers_empty
          申込済みのユーザーは
          %br
          いません。
      - else
        .Takers_count
          = icon('fas', 'user')
          %span
            = "#{@takers.count}人"
        - if user_signed_in? && @user.id == current_user.id
          - @takers.each do |taker|
            = link_to user_path(taker) do
              .Taker_box
                - if taker.profile_image?
                  = image_tag taker.profile_image.url, class: "Taker_box__Image"
                - else
                  = image_tag "no-image.jpg", class: "Taker_box__Image"
                .Taker_box__Name.Text
                  = taker.name

  %hr

  -# ====================================================================================================

  -# 投稿詳細
  .Post_main
    .Post_main__Box
      = link_to 'javascript:history.back()' do
        = icon('fas', 'chevron-left', class: "Back_btn")
      .Post_bookmark
        = render partial: 'favorite', locals: { user: @user, favorite: @favorite, post: @post }
      .Post_show_title.Bold
        = @post.title
      .Tag_list
        - @post.tag_list.each do |tag|
          = link_to posts_g_index_path(tag_name: tag) do
            .tag.Text
              = tag
      - if @post.image?
        = image_tag @post.image.url, class: "Post_image"
      .Post_table.Text
        %table
          %tr
            %th 旅行したい場所
            %td#address
              = @post.region
          %tr
            %th 希望日時
            %td
              = @post.datetime
          %tr
            %th 希望料金
            %td
              = @post.charge
          %tr
            %th お支払い方法
            %td
              = @post.payment
      .Post_head.Bold
        = "-リクエスト内容-"
      .Post_content.Text
        = simple_format(@post.content)
      .Post_head.Bold
        = "-地図-"
      .Post_map#map.Text
    
    -# 申込ボタン
    - if user_signed_in?
      - if @user.id != current_user.id
        - if @post.taker_ids.include?(current_user.id)
          = link_to "申し込みをキャンセルする", cancel_posts_g_path(@post.id), data: { confirm: "こちらの投稿の申し込みをキャンセルしますか？" }, class: "Apply_btn Taken_btn Bold"
        - else
          = link_to "申し込む", take_posts_g_path(@post.id), data: { confirm: "こちらの投稿に申し込みますか？" }, class: "Apply_btn Take_btn Bold"
    - else
      = link_to "申し込む", take_posts_g_path(@post.id), class: "Apply_btn Take_btn Bold"