config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#index'
  resources :users do
    resources :reviews, only: %i[index new create]
    member do
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  resources :posts_g do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_gs, only: %i[create destroy]
  end

  resources :posts_c do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_cs, only: %i[create destroy]
  end

  resources :groups, only: :index do
    resources :messages, only: %i[index create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

  resources :notifications, only: %i[index destroy]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'

  resources :relationships, only: %i[create destroy]

  get '/posts_g/:id/destroy', to: 'posts_g#destroy'
  get '/posts_c/:id/destroy', to: 'posts_c#destroy'

  get '/groups/:id/create', to: 'groups#create'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"

  validates :follower_id, presence: true
  validates :following_id, presence: true

  validates_uniqueness_of :follower_id, scope: :following_id
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  before_action :set_user

  def followings
    @followings = @user.followings
    @followers = @user.followers
  end

  def followers
    @followings = @user.followings
    @followers = @user.followers
  end

  def create
    current_user.follow(@user)
    @user.create_notification_follow!(current_user, @user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
  end

  def destroy
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_url) }
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/relationships/_follow.html.haml
- if user_signed_in?
  -if current_user.following?(user)
    = link_to relationship_path(user.id), method: :delete, remote: true do
      .White_btn.Following
        .White_btn__Content
          = icon('fas', 'user-check')
          = 'フォロー中'
  - else
    = link_to relationships_path(id: user.id), method: :post, remote: true do
      .White_btn
        .White_btn__Content
          = icon('fas', 'user-plus')
          = 'フォロー'
- else
  = link_to relationships_path(id: user.id), method: :post do
    .White_btn
      .White_btn__Content
        = icon('fas', 'user-plus')
        = 'フォロー'

app/views/relationships/_follower.html.haml
- @user = follower

.User_box
  .User_box__Content
    = link_to user_path(@user) do
      - if @user.profile_image?
        = image_tag @user.profile_image.url, class: "User_box__Content__Image"
      - else
        = image_tag "no-image.jpg", class: "User_box__Content__Image"
    .User_box__Content__Text
      = link_to @user.name, user_path(@user), class: "Follow_name"
      .Follow_profile
        = simple_format(@user.profile)
    - unless user_signed_in? && @user == current_user
      %div{class: "Follow-#{@user.id} Follow_list_btn"}
        = render "relationships/follow", user: @user

app/views/relationships/_follower_count.html.haml
= link_to followers_user_path(@user.id) do
  %span
    = @user.followers.count
  = "フォロワー"

app/views/relationships/_following.html.haml
- @user = following

.User_box
  .User_box__Content
    = link_to user_path(@user) do
      - if @user.profile_image?
        = image_tag @user.profile_image.url, class: "User_box__Content__Image"
      - else
        = image_tag "no-image.jpg", class: "User_box__Content__Image"
    .User_box__Content__Text
      = link_to @user.name, user_path(@user), class: "Follow_name"
      .Follow_profile
        = simple_format(@user.profile)
    - unless user_signed_in? && @user == current_user
      %div{class: "Follow-#{@user.id} Follow_list_btn"}
        = render "relationships/follow", user: @user

app/views/relationships/create.js.haml
$('.Follow').html("#{j(render "follow", user: @user)}");
$('.Follow-#{@user.id}').html("#{j(render "follow", user: @user)}");
$('#Follower_count').html("#{j(render "follower_count")}");

app/views/relationships/destroy.js.haml
$('.Follow').html("#{j(render "follow", user: @user)}");
$('.Follow-#{@user.id}').html("#{j(render "follow", user: @user)}");
$('#Follower_count').html("#{j(render "follower_count")}");

app/views/relationships/followers.html.haml
.Title.Flex
  = link_to 'javascript:history.back()' do
    = icon('fas', 'chevron-left', class: "Back_btn")
  = "#{@user.name}さんのフォローリスト"
.Follow_tabs
  = link_to "フォロー中(#{@followings.count})", "#", class: "Follow_tab"
  = link_to "フォロワー(#{@followers.count})", "#", class: "Follow_tab Active"

.Follow_list
  - if @followings.empty?
    .Empty
      = image_tag "foot.jpg", width: "120px"
      %br
      = "フォロー中の"
      %br
      = "ユーザーはいません"
  - else
    = render partial: 'following', collection: @followings

.Follow_list.Show
  - if @followers.empty?
    .Empty
      = image_tag "foot.jpg", width: "120px"
      %br
      = "フォロワーはいません"
  - else
    = render partial: 'follower', collection: @followers

app/views/relationships/followings.html.haml
.Title.Flex
  = link_to 'javascript:history.back()' do
    = icon('fas', 'chevron-left', class: "Back_btn")
  = "#{@user.name}さんのフォローリスト"
.Follow_tabs
  = link_to "フォロー中(#{@followings.count})", "#", class: "Follow_tab Active"
  = link_to "フォロワー(#{@followers.count})", "#", class: "Follow_tab"

.Follow_list.Show
  - if @followings.empty?
    .Empty
      = image_tag "foot.jpg", width: "120px"
      %br
      = "フォロー中の"
      %br
      = "ユーザーはいません"
  - else
    = render partial: 'following', collection: @followings

.Follow_list
  - if @followers.empty?
    .Empty
      = image_tag "foot.jpg", width: "120px"
      %br
      = "フォロワーはいません"
  - else
    = render partial: 'follower', collection: @followers