config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#index'
  resources :users do
    resources :reviews, only: %i[index new create]
    member do
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  resources :posts_g do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_gs, only: %i[create destroy]
  end

  resources :posts_c do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_cs, only: %i[create destroy]
  end

  resources :groups, only: :index do
    resources :messages, only: %i[index create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

  resources :notifications, only: %i[index destroy]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'

  resources :relationships, only: %i[create destroy]

  get '/posts_g/:id/destroy', to: 'posts_g#destroy'
  get '/posts_c/:id/destroy', to: 'posts_c#destroy'

  get '/groups/:id/create', to: 'groups#create'
end

app/models/notification.rb
class Notification < ApplicationRecord
  scope :sorted, -> { order(created_at: :desc) }

  belongs_to :post_g, optional: true
  belongs_to :post_c, optional: true
  belongs_to :group, optional: true
  belongs_to :review, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id'
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id'
  ACTION_VALUES = %w[message review apply_g apply_c cancel_g cancel_c favorite_g favorite_c follow].freeze
  validates :action, presence: true, inclusion: { in: ACTION_VALUES }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    notifications = current_user.passive_notifications
    notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
    @notifications = notifications.where.not(visitor_id: current_user.id).sorted
  end

  def destroy
    notification = Notification.find(params[:id])
    notification.destroy
    redirect_to notifications_path
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.haml
- visitor = notification.visitor
- visited = notification.visited
- post_g = notification.post_g
- post_c = notification.post_c
- group = notification.group



- case notification.action

- when "message" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんから"
        = link_to "メッセージ", group_messages_path(group, user_id: visitor.id)
        = "が届きました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'paper-plane', class: "User_box__Content__Icon")

- when "review" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたの"
        = link_to "レビュー", user_reviews_path(user_id: current_user.id)
        = "を投稿しました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'pen', class: "User_box__Content__Icon")

- when "apply_g" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーゲストの投稿"
        = link_to "「#{post_g.title}」", posts_g_path(post_g)
        = "を申し込みました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'check-circle', class: "User_box__Content__Icon")

- when "apply_c" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーキャストの投稿"
        = link_to "「#{post_c.title}」", posts_c_path(post_c)
        = "を申し込みました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'check-circle', class: "User_box__Content__Icon")

- when "cancel_g" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーゲストの投稿"
        = link_to "「#{post_g.title}」", posts_g_path(post_g)
        = "をキャンセルしました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'times-circle', class: "User_box__Content__Icon")

- when "cancel_c" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーキャストの投稿"
        = link_to "「#{post_c.title}」", posts_c_path(post_c)
        = "をキャンセルしました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'times-circle', class: "User_box__Content__Icon")

- when "favorite_g" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーゲストの投稿"
        = link_to "「#{post_g.title}」", posts_g_path(post_g)
        = "をお気に入りに追加しました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'bookmark', class: "User_box__Content__Icon")

- when "favorite_c" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたのツアーキャストの投稿"
        = link_to "「#{post_c.title}」", posts_c_path(post_c)
        = "をお気に入りに追加しました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'bookmark', class: "User_box__Content__Icon")

- when "follow" then
  .User_box
    .User_box__Content
      = link_to user_path(visitor) do
        - if visitor.profile_image?
          = image_tag visitor.profile_image.url, class: "User_box__Content__Image"
        - else
          = image_tag "no-image.jpg", class: "User_box__Content__Image"
      .User_box__Content__Text
        = link_to visitor.name, user_path(visitor)
        = "さんがあなたをフォローしました。"
        .Notification_time
          = notification.created_at.strftime("%-m月%-d日 %-H:%M")
      = link_to "×", notification_path(notification.id), method: :delete, class: "User_box__Content__Destroy"
      = icon('fas', 'user-plus', class: "User_box__Content__Icon")

app/views/notifications/index.html.haml
.Notification_head
  .Notification_head__Content
    = link_to 'javascript:history.back()' do
      = icon('fas', 'chevron-left', class: "Back_btn")
    .Title 通知一覧
  - if @notifications.exists?
    = link_to notifications_destroy_all_path, data: { confirm: "通知を全て消去しますか？" }, class: "Notification_destroy_all" do
      = icon('fas', 'trash')
      = "全ての通知を消去する"
- if @notifications.exists?
  %hr
  = render @notifications
- else
  .Empty
    = image_tag "foot.jpg", width: "120px"
    %br
    = "通知はありません"