config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'home#index'
  resources :users do
    resources :reviews, only: %i[index new create]
    member do
      get 'followings', to: 'relationships#followings'
      get 'followers', to: 'relationships#followers'
    end
  end

  resources :posts_g do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_gs, only: %i[create destroy]
  end

  resources :posts_c do
    member do
      get 'take'
      get 'cancel'
    end
    resource :favorite_cs, only: %i[create destroy]
  end

  resources :groups, only: :index do
    resources :messages, only: %i[index create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end

  resources :notifications, only: %i[index destroy]
  get '/notifications/destroy_all', to: 'notifications#destroy_all'

  resources :relationships, only: %i[create destroy]

  get '/posts_g/:id/destroy', to: 'posts_g#destroy'
  get '/posts_c/:id/destroy', to: 'posts_c#destroy'

  get '/groups/:id/create', to: 'groups#create'
end

app/models/user.rb
class User < ApplicationRecord
  # ユーザー
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 10 }

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: "ゲスト") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  mount_uploader :profile_image, ImageUploader

  # 投稿
  has_many :giving_post_gs, foreign_key: "giver_id", class_name: "PostG", dependent: :destroy
  has_many :giving_post_cs, foreign_key: "giver_id", class_name: "PostC", dependent: :destroy

  has_many :post_g_takers, foreign_key: "taker_id", dependent: :destroy
  has_many :taking_post_gs, through: :post_g_takers, source: :taking_post_g, dependent: :destroy
  has_many :post_c_takers, foreign_key: "taker_id", dependent: :destroy
  has_many :taking_post_cs, through: :post_c_takers, source: :taking_post_c, dependent: :destroy

  has_many :favorite_gs, dependent: :destroy
  has_many :favorite_cs, dependent: :destroy

  # メッセージ
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :messages, dependent: :destroy

  # レビュー
  has_many :reviews, foreign_key: "reviewee_id", dependent: :destroy

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1)
    end
  end

  # 通知
  has_many :active_notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  # フォロー
  has_many :following_relationships, foreign_key: "following_id", class_name: "Relationship",  dependent: :destroy
  has_many :followings, through: :following_relationships, source: :follower
  has_many :follower_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :following

  def following?(other_user)
    followings.include?(other_user)
  end

  def follow(other_user)
    following_relationships.create(follower_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(follower_id: other_user.id).destroy
  end

  def create_notification_follow!(current_user, user)
    notification = current_user.active_notifications.new(
      visited_id: user.id,
      action: 'follow'
    )
    notification.save if notification.valid?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    redirect_to edit_user_registration_path, alert: 'ゲストユーザーの変更・削除はできません。' if params[:user][:email].downcase == 'guest@example.com'
  end

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def edit
    @user = User.find(current_user.id)
  end

  def check_guest
    redirect_to edit_user_registration_path, alert: 'ゲストユーザーの変更・削除はできません。' if resource.email == 'guest@example.com'
  end

  # private

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_user, except: :update
  layout 'no_wrapper', only: :show

  def show
    # 投稿一覧
    @giving_post_gs = @user.giving_post_gs
    @giving_post_cs = @user.giving_post_cs

    # 申込あり
    post_g_ids = PostGTaker.pluck(:post_g_id)
    @taken_post_gs = PostG.where(id: post_g_ids).where(giver_id: @user.id)
    post_c_ids = PostCTaker.pluck(:post_c_id)
    @taken_post_cs = PostC.where(id: post_c_ids).where(giver_id: @user.id)

    # 申込済み
    @taking_post_gs = @user.taking_post_gs
    @taking_post_cs = @user.taking_post_cs

    # お気に入り
    favorite_g_ids = @user.favorite_gs.pluck(:post_g_id)
    @favorite_gs = PostG.where(id: favorite_g_ids)
    favorite_c_ids = @user.favorite_cs.pluck(:post_c_id)
    @favorite_cs = PostC.where(id: favorite_c_ids)

    # レビュー
    reviews = Review.where(reviewee_id: @user.id)
    @count = reviews.count

    # メッセージ
    return unless user_signed_in?

    group_ids = @user.groups.pluck(:id)
    group_users = GroupUser.where(group_id: group_ids)
    group_user = group_users.where(user_id: current_user.id)
    @group_id = group_user.pluck(:group_id).first
  end

  def edit; end

  def update
    if current_user.update(user_params)
      flash[:notice] = 'プロフィールを編集しました。'
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = 'プロフィールを編集できませんでした。'
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:id, :name, :email, :profile_image, :profile)
  end
end

app/views/users/edit.html.haml
= javascript_include_tag 'userImage'

.Title.Form_title
  = link_to 'javascript:history.back()' do
    = icon('fas', 'chevron-left', class: "Back_btn")
  = "プロフィールを編集する"
.Edit_profile_image
  - if current_user.profile_image?
    = image_tag current_user.profile_image.url, class: "Profile_image", id: "Img_prev"
  - else
    = image_tag "no-image.jpg", class: "Profile_image", id: "Img_prev"
.Edit_profile_form
  = form_for(current_user) do |f|
    = f.label :profile_image, "画像を選択", class: "Edit_profile_form__Btn"
    = f.file_field :profile_image, class:"Image_select", style: "display:none;"
    %br
    = f.label "自己紹介文", class: "Profile_label"
    %br/
    = f.text_area :profile, autofocus: true, rows: "10", class: "Form__Content__Field--Large"
    = f.submit "保存", class: "Btn Text"

app/views/users/show.html.haml
.Mypage_header
  .Mypage_header__Content
    = link_to 'javascript:history.back()' do
      = icon('fas', 'chevron-left', class: "Back_btn")
    .Header_user_name
      - if user_signed_in? && @user.id == current_user.id
        = "マイページ"
      - else
        = @user.name
.Mypage_wrapper
  .Mypage_wrapper__Inner


    -# ========== 上部 ==========
    .Mypage_upper

      -# ========== サイドバー（ユーザー） ==========
      - if user_signed_in? && @user.id == current_user.id
        .Mypage_side_bar
          = link_to groups_path do
            .Mypage_side_bar_row
              = icon('fas', 'paper-plane')
              .Mypage_side_bar_btn
                トークルーム
          = link_to notifications_path do
            .Mypage_side_bar_row
              - if unchecked_notifications.any?
                %span.fa-stack
                  = icon('fas', 'bell',  class: "fa-stack-2x")
                  = icon('fas', 'circle',  class: "fa-stack-1x")
              - else
                = icon('fas', 'bell', class: 'Bell')
              .Mypage_side_bar_btn
                通知
          = link_to edit_user_registration_path do
            .Mypage_side_bar_row
              = icon('fas', 'user-edit')
              .Mypage_side_bar_btn
                = "アカウントの編集"
          = link_to users_sign_out_path, method: :delete, data: { confirm: "ログアウトしますか？" } do
            .Mypage_side_bar_row
              = icon('fas', 'sign-out-alt')
              .Mypage_side_bar_btn
                = "ログアウト"

      -# ========== プロフィール ==========
      .Mypage_upper__Main
        .Profile
          .Profile__Upper
            - if @user.profile_image?
              = image_tag @user.profile_image.url, class: "Profile_image"
            - else
              = image_tag "no-image.jpg", class: "Profile_image"
            .Profile_content
              .Name
                = @user.name
              .Mypage_review
                .Star_rating
                  = image_tag "stars.jpg", class: "Front", width: "#{@user.avg_score*20}%"
                  = image_tag "stars_gray.jpg"
                .Review_info
                  = @user.avg_score
                  = link_to "(#{@count}件のレビュー)", "/users/#{@user.id}/reviews"
              .Mypage_follow_counts
                .Mypage_follow_count
                  = link_to followings_user_path(@user.id) do
                    %span
                      = @user.followings.count
                    = "フォロー"
                .Mypage_follow_count#Follower_count
                  = render "relationships/follower_count"
            .Mypage_btns
              - if user_signed_in?
                - if @user.id == current_user.id
                  = link_to edit_user_path(current_user) do
                    .White_btn.Profile_edit_btn
                      .White_btn__Content
                        = icon('fas', 'user-edit')
                        = "プロフィールの編集"
                - else
                  .Follow
                    = render "relationships/follow", user: @user
                  - if @group_id.nil?
                    = link_to "/groups/#{@user.id}/create" do
                      .White_btn
                        .White_btn__Content
                          = icon('fas', 'paper-plane')
                          = "メッセージを送る"
                  - else
                    = link_to group_messages_path(@group_id, user_id: @user.id) do
                      .White_btn
                        .White_btn__Content
                          = icon('fas', 'paper-plane')
                          = "メッセージを送る"
              - else
                .Follow
                  = render "relationships/follow", user: @user
                = link_to "/groups/#{@user.id}/create" do
                  .White_btn
                    .White_btn__Content
                      = icon('fas', 'paper-plane')
                      = "メッセージを送る"
          .Profile__Lower
            = simple_format(@user.profile)


    -# ========== 下部 ==========
    .Mypage_lower

      -# ========== サイドバー（投稿） ==========
      - if user_signed_in? && @user.id == current_user.id
        .Mypage_side_bar.Mypage_side_bar_post
          .Post_type_btns_title_row
            = icon('fas', 'edit', class: 'Post_type_btns_title')
            .Post_type_btns_title 投稿
          = link_to "#" do
            .Mypage_side_bar_row.Post_type_btn.Active1
              = icon('fas', 'list')
              .Mypage_side_bar_btn
                投稿一覧
          = link_to "#" do
            .Mypage_side_bar_row.Post_type_btn
              = icon('fas', 'user')
              .Mypage_side_bar_btn
                申込あり
          = link_to "#" do
            .Mypage_side_bar_row.Post_type_btn
              = icon('fas', 'check-circle')
              .Mypage_side_bar_btn
                申込済み
          = link_to "#" do
            .Mypage_side_bar_row.Post_type_btn
              = icon('fas', 'bookmark')
              .Mypage_side_bar_btn
                お気に入り

      -# ========== 投稿一覧 ==========
      .Mypage_lower__Main
        .User_page_tabs
          = link_to "ツアーゲストの投稿", "#", class: "User_page_tab Active2"
          = link_to "ツアーキャストの投稿", "#", class: "User_page_tab"
        
        .Mypage_lower__Content.Show1
          .Mypage_posts.Show2{data: {content: "0"}}
            - if @giving_post_gs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @giving_post_gs.each do |post|
                  = render partial: "posts_g/post", locals: { post: post }
          .Mypage_posts{data: {content: "0"}}
            - if @giving_post_cs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @giving_post_cs.each do |post|
                  = render partial: "posts_c/post", locals: { post: post }

        .Mypage_lower__Content
          .Mypage_posts.Show2{data: {content: "1"}}
            - if @taken_post_gs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @taken_post_gs.each do |post|
                  = render partial: "posts_g/post", locals: { post: post }
          .Mypage_posts{data: {content: "1"}}
            - if @taken_post_cs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @taken_post_cs.each do |post|
                  = render partial: "posts_c/post", locals: { post: post }

        .Mypage_lower__Content
          .Mypage_posts.Show2{data: {content: "2"}}
            - if @taking_post_gs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @taking_post_gs.each do |post|
                  = render partial: "posts_g/post", locals: { post: post }
          .Mypage_posts{data: {content: "2"}}
            - if @taking_post_cs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @taking_post_cs.each do |post|
                  = render partial: "posts_c/post", locals: { post: post }

        .Mypage_lower__Content
          .Mypage_posts.Show2{data: {content: "3"}}
            - if @favorite_gs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @favorite_gs.each do |post|
                  = render partial: "posts_g/post", locals: { post: post }
          .Mypage_posts{data: {content: "3"}}
            - if @favorite_cs.empty?
              = render "layouts/empty"
            - else
              .Post_index
                - @favorite_cs.each do |post|
                  = render partial: "posts_c/post", locals: { post: post }